//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Name { get; set; }
        public int Position { get; set; }
        public int tabNum { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
